import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/app/components/Notification/ToastProvider";
import Navbar from "./components/navbar";
import { HeaderAccountPanel } from "./components/HeaderAccountPanel";
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Currency Prices",
  description: "Generated by create Hasan Afif",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar>
          <Suspense fallback={<h2>Loading...</h2>}>
            <HeaderAccountPanel />
          </Suspense>
        </Navbar>
        {children}
        <ToastProvider />
      </body>
    </html>
  );
}
